### ISSUE TITLE
GUI bugs

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#10]
1.Zamaknjena 'Bookmarks' in 'Notebook' napisa
2.Children gumb ima na tablici sliko otrok preveliko in rahlo navzdol zamaknjeno 
3.Na nobeni napravi ni več fug pri spodnjih dveh gumbih
![20141018_025848](https://cloud.githubusercontent.com/assets/9002153/4687954/a2e4b61e-5662-11e4-900d-03a194b9914f.jpg)
![20141018_025747](https://cloud.githubusercontent.com/assets/9002153/4687955/a2eaaee8-5662-11e4-9fe4-6c9d82b8e5fc.jpg)

**Comment by NejcDraganjec** [comment]
1. točka (Zamaknjena 'Bookmarks' in 'Notebook' napisa): že razrešena v drugem bug reportu.
2. točka: enako
3. točka: popravljen xml sklic android:padding="1dp" v android:layout_margin="1dp"
