### ISSUE TITLE
GUI po prvem zaslonu ne dela na dodatnih dimenzijah (Tablet recimo)

### ISSUE THREAD

**Issue by NejcDraganjec** [NejcDraganjec/Qiuba_BugTrack#18]
Gumbi ne delajo. Verjetno bo treba definirati dodatne layoute za različne dimenzije tudi na drugih nivojih.

**Comment by NejcDraganjec** [comment]
Če se prav spomnim smo to potem zrihtali. In je bil točno ta problem, kot sem ga predvideval v komentarju zgoraj. Tudi na mojem simulatorju dela. Za enkrat zapiram, če slučajno še kje kaj škripa naj se pa odpre nova kartica.

**Comment by ghost** [comment]
Zmenjeno. Emulator kdaj ni enako kot dejanska naprava, kdaj bom pa spet imel kakšno tablico v rokah pa vprašanje. Do takrat je to lahko zaprto.
