### ISSUE TITLE
GUI Therapy screen #8 - UP ARROW

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#19]
Implementacija UP ARROW v Therapy screen

**Comment by NejcDraganjec** [comment]
Gumb "za nazaj" na prejšnje zaslone (v androidu se imenuje up arrow) ali za na vrh zaslona kadar si "priskrolau" nekam daleč dol po seznamu?

**Comment by ghost** [comment]
Druga opcija, ampak je ne rabimo se mi zdi. Tako da zapiram temo.
