### ISSUE TITLE
Časovno zaklepanje aplikacije

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#21]
Aplikacijo se mora zakleniti za rok 1 leta od roka prve instalacije, mora omogočati ponoven zakup enega leta (in vsakega naslednjega).

Za testirance moramo implementirati zaklep po 6 mesecih po nalaganju iz Google Play. Ker smo imeli namen dobiti testirance na kongresih in jim tam ponudit vprašalnik in kot nagrado aplikacijo za pol leta, moramo zdaj potencialne pozameznike preizkuševalce nekako stimulirati. Tako da se naj jim po 7 dneh aplikacija zaklene, če ne oddajo vprašalnika. Potem pa mora biti nekakšen ukaz z naše strani, da je oddal vprašalnik, in da se mu podaljša za pol leta. Lahko imamo tudi dve različni verziji - to za preizkuševalce, in pa uradno, pa se po pol leta za vedno izklopi aplikacija in se jim ponudi link na Googlu, kjer lahko zakupijo aplikacijo za eno leto (torej ta uradna verzija bi imela samo en zaklep - po enem letu, za preizkuševalce verzija pa bi imela zaklep 7 dni in potem po pol leta neha delat)

**Comment by NejcDraganjec** [comment]
Done and done.

**Comment by NejcDraganjec** [comment]
Zapiram kartico...

**Comment by ghost** [comment]
Kako bi pa lahko to zaklepanje preverili sploh če dela?

**Comment by NejcDraganjec** [comment]
Jaz sem v emulatorju, s spremembo datuma na fizični napravi in z ročnim dodatkom podatka v RDB. Delalo po vseh možnih kanalih, tako da ponovno zapiram :).
