### ISSUE TITLE
Back button v orodni vrstici

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#22]
Back button v orodni vrstici skoči na Main screen glede na nivo v katerem smo, namesto, da bi šel za en nivo nazaj. Obnaša se kot home button. Če kliknemo ta gumb v 'General' se celo sesuje aplikacija.

Sva pa razmišljala z Valentino, za en nivo nazaj lahko uporabnik uporabi gumb za nazaj na sami napravi. Tako da je lahko v orodni vrstici aplikacije tam kjer je zdaj gumb za nazaj (ki se zdaj obnaša kot Home button) dejansko Home button = hiška, ki bi ohranila funkcijo = vrne uporabnika v Main screen.

Kaj misliš?

**Comment by NejcDraganjec** [comment]
Še star problem z aktivnostno vrstico. Če prav vem je sedaj to že zdavnaj rešeno. Zapiram kartico, če ni naj se pa ponovno odpre pa malo bolj opiše kje je problem (back button, ki se v androidu imenuje up button je pravzaprav home button. Ja, zmeda. SKratka, zadeva je dost zakomplicirana in moreš povozit predvideno obnašanje t.i. "back stack" aktivnosti).

**Comment by ghost** [comment]
Zdaj je v redu. Over and out
