### ISSUE TITLE
Manjkajoče terapije v Alternativni terapiji

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#23]
Da se izognemo nejasnostim s strani uporabnika, naj bo v primeru, da je Alternativna terapija prazna, napisano 'Alternative therapy is not available.'

Če je kje slučajno prazno v 'Therapy of choice' in je terapija samo v 'Alternative therapy', se prestavi terapijo iy alternative v terapijo izbire. (to je nekaj v databazi popravljala že Valentina, se bo pa moralo poklikati kje so taki primeri še ostali, in lahko to dopolniva tudi midva)

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico.

**Comment by ghost** [comment]
To bom lahko preveril šele, ko spet inštaliram zadnji APK (imam outdate-ano verzijo projecta v Android Studiu). Do takrat bom ponovno odprl (da ne pozabim), in takoj zaprl, ko preverim.
