### ISSUE TITLE
Tekst v General

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#24]
Poravnava teksta bi lepše zgledala kot obojestranska poravnava.

Potence v general (10 na deveto) so sedaj brez superscript. Izpade kot '109', namesto potenca.

Si to hardcode-al v aplikacijo, ali je General tekst v databazi (Valentina bi popravila slovnične napake, presledke, ipd.)?

**Comment by NejcDraganjec** [comment]
Poravnavo se določi v predlogi znotraj aplikacije. Kako bodo prikazane številke (recimo 10^9) pa v DB. V DB torej poravljata vidva, za poravnavo teksta pa povejta, če spremenim. Za enkrat puščam odprto, če sta pa že popravila v DB in sta se glede obojsestranske poravnave premislila, pa kar zaprita.

**Comment by ghost** [comment]
Potence sva popravila v DB, obojestransko poravnavo pa bi rada imela še vedno (v General in če je možno tudi v opombah?).

**Comment by NejcDraganjec** [comment]
Opombah? Misliš anotacijah, zapiskih ali kaj drugega?

**Comment by NejcDraganjec** [comment]
OK, po pregledu opcij je sklep, da android ne podpira polne obojestranske poravnave ("justifiy"). Ne v kontekstu kot imamo narejeno sedaj, kjer so nosilci teksta kontejnerji tipa textView. Možno bi bilo s presedlanjem na nosilce webView, kar lahko ostane potencialna opcija za kakšno posodobitev v prihodnje. Za enkrat pa zapiram kartico.

**Comment by ghost** [comment]
Zdej sm na hitro preveru ta webView. Informativno, če bi po tej verziji presedlal na webapp in pokril iOS in Android, kaj bi to pomenilo, bi gumb za anotacije lahko skenslal in implementiral hyperlinke kajne?

Ker poznam samo Phonegap od teh programov, ki naredijo iOS in Android aplikacijo, me zanima, če je webView tudi podobna zadeva? Če se odločimo (nismo niti še govorili o tem, se pa sam zelo nagibam k tej opciji), bi ti to se lotil / znal narediti?
