### ISSUE TITLE
Knjižnica ikon

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#25]
Bi nama lahko poslal knjižnico ikon, za finalno verzijo? Ali sama kje najdeva knjižnico V tem primeru bi te prosil, za link-e uporabnih strani.

Rada bi našla lepo ikono za anotacije, vem pa, da sva rekla da se bo to itak spreminjalo. To bi pač zdaj lahko z Valentino izbrala že sedaj, samo doreči moramo katero knjižnico bomo uporabljali. 

Sedaj je prikazna ikona aplikacije v meniju telefona manjša kot ostale. Če se prav spomnim, lahko to (vsaj v Eclipse) nastaviš na začetku, ko odpreš nov projekt (verjetno pa tudi tekom projekta). Rada bi, da je ta 'Q' ikona največja kar je možno za te ikone v menijih, z zaobljenimi robovi.

**Comment by NejcDraganjec** [comment]
Sva že rešila preko FB. Uraden nabor ikon (ki ga priporoča in predpisuje kar google sam) je pa na povezavi:
https://developer.android.com/design/downloads/index.html

**Comment by ghost** [comment]
Over and out.
