### ISSUE TITLE
Ime aplikacije

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#26]
V meniju telefona je kratka verzija imena = 'Quiba'. Ko pridemo v aplikacijo pa bi bilo dobro, da bi bil napisan celoten ime aplikacije = 'Quiba: Simple Guide to Antimicrobials'

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico.

**Comment by ghost** [comment]
Tako kot sem rekel, 'Quiba' naj bo pod launcher ikono in v orodni vrstici. Je predolgo celotno ime tudi za orodno vrstico, tako da bo polno ime samo v Google Play trgovini in v Licence Agreementu (ki ga še vedno čakam s strani g.Huča)
