### ISSUE TITLE
Prazni General screeni

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#27]
Pogruntati moramo pametno rešitev situacije, ko tekst v General ni na voljo, torej ga sploh ni. V tem primeru je gumb clickable in se odpre prazen zaslon, kar ni v redu.

En predlog je, da se gumb izklopi, tako da se obarva svetlo sivo. Tako bi uporabnik vedel, da gumb ni aktiven.

**Comment by NejcDraganjec** [comment]
Ta predlog dodatno obremeni aplikacijo in odzivnost vmesnika. Ga odsvetujem. Predlagam da se naredi tako kot npr. pri terapijah. General, ki nima vsebine na to opozori s tekstom.

**Comment by ghost** [comment]
Se mi zdi, da sem v enem drugem (zaprtem?) 'issue'-u napisal že, pa bom ponovil še tukaj. Če si že odgovoril, se opravičujem za ponavljanje. 
V takih primerih bi vstavila tekst 'No general information about this topic is available in this version of Quiba.'
Popraviva to midva v databazi (in če, kje?) ali bi ti?

**Comment by NejcDraganjec** [comment]
Ja, to je stvar programiranja. Bom dodal...

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico.
