### ISSUE TITLE
Slike v General 

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#29]
Tabele, ki so notri kot slike, bi bilo smiselno klikniti, da se odpre slika ali kaj podobnega. Dejstvo je, da se že na phabletu Note 4, z relativno veliki zaslonom, ne vidi, kaj je v teh tabelah napisano. S pinch in gesto pa ne moremo povečati te slike.

Potrebno je najti način, da povečamo sliko, da uporabnik sploh lahko prebere kaj dol.

**Comment by NejcDraganjec** [comment]
Se jih da. Problem je drugje in sicer verjetno v istem delu kot je z "queriji" označen na drugih delih (recimo anotacije na therapy screen). Za enkrat je tako, da program pogleda dimenzije slike in zaslona in odpre sliko v maksimalnem  načinu (če je širša kot višja v landscape, če je višja kot širša pa obratno). Problem je, ker se resetira ko sproži zamenjavo orientacije iz portretnega načina v landscape in se zato slika ne pokaže. Če se sliko potem klikne še enkrat se pa. Neki bo treba še pogruntat glede tega. Pinch zoom pa ne bo deloval v nobenem primeru. Kvečejmu če bi za take primere sprožili zunanjo aplikacijo za odpiranje in gledanje slik.

**Comment by ghost** [comment]
No moja brainstorming rešitev No.1 je, da glede na to da so v slikah tako al tako samo tabele, dejansko ustvarmo tabele v general delih. Tako ne bodo več slike, aplikacija bo pa prilagodila širine in višine celic tabel glede na velikost naprave?

**Comment by NejcDraganjec** [comment]
Not so easy :). Tole bi bila res skrajna rešitev v brezizhodni situaciji.

**Comment by NejcDraganjec** [comment]
Done and done. Dodal sem podporo za več-dotik in "pinch-zoom". Pa še za "double tap". Sedaj slike ne odpre več v novem oknu ampak jo lahko zoomiraš z gestami na njenem mestu.

**Comment by NejcDraganjec** [comment]
Zapiram kartico ...
