### ISSUE TITLE
Galaxy ace2 anotacije bug

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#30]
V kategorijah ne mores sploh kliknit na ikono za anotacije brez da bi kliknil in odprl kar dejansko kategorijo.
V therapy screenu pa anotacije odpres samo s klikom zgoraj desno na ikono. Odprta anotacija pa ni berljiva.

**Comment by ghost** [comment]
p.s.: ni berljiva, če je tekst daljši od prostora v pop-up oknu. Tudi scrollanje teksta ni možno

**Comment by ghost** [comment]
Update: ista stvar z zadnjo verzijo aplikacije tudi še ne dela. Plus, ko se že odpre anotacija in je tekst predolg, se ga ne more scrollat in tako ne moreš prebrati več kot nekaj prvih besed anotacije.

Link: https://drive.google.com/file/d/0B0c8XrM0mazqOXNmSDRLRi1WVTVOczY2MDhPaE83WkUzY3hF/view?usp=sharing

Kaj je sploh problem v tem bug-u?

**Comment by NejcDraganjec** [comment]
Na posnetku vidim problem z odpiranjem, ne vidim pa problema z berljivostjo. Prvi vtis je, da je problem v Samsungih in njihovi verziji androida, ki je drugačana od glavnega forka. Vprašanje je kaj če sploh kaj lahko glede starih verzij samsungov naredimo. Bom malo pogooglal...

**Comment by ghost** [comment]
Problem z berljivostjo se vidi tudi na tem videu, če pozorno pogledaš prvo opombo ima na koncu tri pikice (...). To pomeni da se opomba nadaljuje, ampak je ne morem prebrati. Tudi če kliknem na to konkretno ikono. To je skozi aplikacijo na tej napravi (na vseh manjših napravah?) pravilo in ne izjema.

No sporoči kaj, če kaj sploh, lahko naredimo glede tega. Kot rečeno že nekje drugje, bi lahko prišla v poštev za te stare verzije kakšna modificirana izdaja aplikacije samo za te starejše verzije (seveda kaj točno bi se pa moralo potweekati samo za te naprave da bi delalo OK si pa ne predstavljam)?

**Comment by NejcDraganjec** [comment]
Bom preveril. Je pa to čisto muha tega segmenta mobitelov. Anotacije, ki so večje od zaslona drugače kreirajo scroll view samodejno, pri tem mobitelu pa tega očitno ni v knjižnici. Zakaj pri darwinu ne, pa pojma nimam! Bom preveril kakšne so možnosti da kreiranje scroll view izsilimo...

**Comment by NejcDraganjec** [comment]
Primer problema na 480x800, API10:

![screenshot from 2015-03-01 19 46 03](https://cloud.githubusercontent.com/assets/6403001/6432323/18594ac8-c04d-11e4-81ad-5772b532131b.png)

**Comment by NejcDraganjec** [comment]
Primer prav tako Samsunga (Galaxy S2), s primerljivo velikostjo zaslona 480x800, kjer pa nobenih opisanih težav ni (nepojasnjeno krajšanje anotacije, težave s klikanjem na ikono anotacije, ...). Problem torej v starejših API-jih...

![screenshot from 2015-03-01 22 43 57](https://cloud.githubusercontent.com/assets/6403001/6433013/cc033aae-c064-11e4-8e1f-80d173f7a624.png)

**Comment by NejcDraganjec** [comment]
Done and done. Odpravljeni problemi s klikanjem na ikono in s okrajševanjem teksta, ko se enkrat anotacija prikaže. Zapiram kartico.
