### ISSUE TITLE
Kartice v Bookmarks/Notes

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#34]
Ko se začne drobtinica je npr. 'diseases adults', bi se lahko začelo z veliko začetnico in brez diseases, tako kot imamo v Main meniju --> Adults/...

**Comment by NejcDraganjec** [comment]
V meniju je zakodirano poimenovanje v gumbke. V tem primeru se vleče iz podatkovne zbirke. Če želita da je drugače spremenita tam, tako da bo povsod poenoteno (oba notes in bookmarks pa še navigation drawer). Zapiram kartico.
