### ISSUE TITLE
Tablica NOBIS NB7022 S - napaka pri izpisovanju General v Children

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#36]
https://drive.google.com/file/d/0B0c8XrM0mazqMThROEJGblNqdDA/view?usp=sharing
Na zgornjem linku je video do napake. V prvih 10sec je vidno tudi, da mi je v Gastrointestinal tract v Children odprlo General, a mi tudi v tem primeru ne pokaže gumba za breadcrumb, da se lahko vrnem nazaj. Moraš kar pomisliti, preden klikneš tipko za nazaj na napravi in ne v aplikaciji (ker je v tem primeru itak ni). 

@28sec: pridem do General zavihka pod Abdomen, ki pa ne dela. To se pojavlja čez celo aplikacijo, razen v redkih izjemah, ko dela.

Mogoče bi za te tablice tudi zaklenili, in izdali v naslednjih verzijah aplikacije tudi eno verzijo prilagojeno za take tablice. (itak je to pri Androidu kar pogosto, kar berem, da morajo podjetja izdati več verzij iste aplikacije za različne naprave). Mnenje?

**Comment by NejcDraganjec** [comment]
General in references nimajo gumbka za nazaj. Lahko dodamo, v tem primeru oddajta novo zahtevo kot enhancement. Napaka pa izgleda kot stara že popravljena napaka, ko še ni pravilno delal navigation drawer. Zaenkrat zapiram, če se isti problem pojavlja tudi v zadnji verziji pa še enkrat odprita.

**Comment by ghost** [comment]
V Children/Abdomen/General sploh ni teksta niti v databazi. Smo pa rekli da se v teh primerih napiše nek text kot: No content available. Napiševa to midva v databazi?

**Comment by NejcDraganjec** [comment]
Stvar druge kartice. Osnovno obvestilo kadar ni teksta je sprogramirano. Bom dodal, to kartico pa zapiram.
