### ISSUE TITLE
Annotation screen - Samsung Ace 2 - čuden hrošč

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#37]
Poglej posnetek:
https://drive.google.com/file/d/0B0c8XrM0mazqVnhrVzJBZmltUDQ/view?usp=sharing

**Comment by NejcDraganjec** [comment]
Ni hrošč. Predvideno delovanje androida na long touch je da izbere element in pomodri ozadje. Tekst nima ozadja zato se v močni modrini izgubi. Zapiram kartico.

**Comment by ghost** [comment]
Zakaj pa ne pomodri v Note 4 (sklepam da drugih napravah tudi, a jih nimam pri sebi da bi lahko dejansko potrdil)? V Note4 posivi ozadje a se tekst  še vedno vidi (tekst je črne barve)... Tukaj tudi ostane a močno obarvanje ozadja modro prepreči da bi se kaj videlo. Je različna barva obarvanja ozadja stvar naprave ali aplikacije?
