### ISSUE TITLE
Predlog za izboljšavo drobtinic

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#38]
'Therapy screen' izraz je med nami uveljavljen izraz, ki pa pri uporabniku izpade malo čudno. Boljše je, da namesto 'THERAPY SCREEN: bla bla bla' v drobtinicah piše 'THERAPY: bla bla bla'.

Opcionalno: Se da za trenutno odprti nivo (katerikoli nivo, od Adults naprej; ne samo v konkretnem primeru odprt therapy screen) uporabiti bold pisavo?

https://drive.google.com/file/d/0B0c8XrM0mazqTEpYN1FwVXhVdjg/view?usp=sharing

**Comment by NejcDraganjec** [comment]
Sem spremenil therapy screen v therapy in pathogen screen v pathogen. Kar se bold fonta tiče, pa odsvetujem. Prvič ne zgleda ok, drugič je pa križ, ker uporabljamo zunanji font, ki pa odebljenih črk nima (zaradi zmanjšanja velikosti aplikacije in zaradi pohitritve delovanja). Tako da s tem so sami križi. Za enkrat kartico zapiram.

**Comment by ghost** [comment]
Ok, super.
