### ISSUE TITLE
Notification ikone

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#39]
Naredil sem notifikacijske ikone, ne vem pa v katero mapo (drawable?) naj jih vržem. Tudi sicer, ko bo na voljo update, in bo Android ponudil uporabniku posodobitev, se mora ta ikona pokazati zgoraj levo na telefonu. Moraš to nekam v kodo sprogramirati, da aplikacija ve katero ikono mora uporabit, ali kako gre to? 
V bistvu sta na tem naslovu: http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example možni dve verziji notification ikon, in zdaj imam obe. Damo v aplikacijo obe verziji in potem aplikacija sama zazna verzijo androida na telefonu in se odloči, katero verzijo notification ikon uporabi?

Ikona 1 (bela!): ![ic_stat_notification_original](https://cloud.githubusercontent.com/assets/9002153/6174480/4deabb74-b2ef-11e4-81fc-481b8c590d45.png)
Ikona 2 (temna): ![ic_stat_notification_original](https://cloud.githubusercontent.com/assets/9002153/6174481/5617952e-b2ef-11e4-94a7-7404775ed57a.png)

**Comment by NejcDraganjec** [comment]
Se ne navezuje na delovanje quibe in te funkcionalnosti app ne koristi. Bolj natančno že razolženo po telefonu in/ali FB. Zapiram kartico.
