### ISSUE TITLE
Velikost launcher ikone

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#40]
Karkoli poskusim, je launcher ikona vedno manjša od preostalih aplikacij na aparatih (na Ace2 je manjši zaslon in so razlike v desetinkah milimetra, bolj opazno je na večjem Note4). 
![appiconace2](https://cloud.githubusercontent.com/assets/9002153/6174728/f7ab2c2e-b2f0-11e4-9fea-3269858e35cc.png)
![appiconnote4](https://cloud.githubusercontent.com/assets/9002153/6174727/f7aae62e-b2f0-11e4-90d1-d48170cfbdc3.png)

Zaenkrat sem poskusil sledeče:
1.) V Drawable xxhdpi mapi sem pustil ikono, v manjših sem jo izbrisal. (uporabil sem Launcher Icon Generator) --> launch ikona ostane manjša od ostalih aplikacij
2.) V Drawable mapah sem uporabil največji size (200 dip) (uporabil sem Generic Icon Generator, ker v Launcher Icon Generator ne moreš izbrati velikosti ikone) --> launch ikona je na manjšem zaslonu Ace2 kockasta, ker zelo veliko sliko hoče zbasat v več pikslov na inch kot jih dejansko aparat premore; na Note4 ni kockasta; na obeh telefonih je launch ikona manjša kot pri ostalih aplikacijah
3.)poskusil sem narediti original launch ikono 1024x1024 namesto 512x512, ampak je rezultat isti, saj generator ikon na koncu vrže ven enako velike ikone v obeh primerih (saj je logično, ampak sem vseeno puskusil)
4.)Na http://iconhandbook.co.uk/reference/chart/android/ sem prebral, da je baseline za mdpi: 160 dpi. V Inkscape-u, v katerem urejam vektorske slike, sem izvozil sliko s 160dpi, kar mi da sliko velikosti 910x910. 
4.1) Poskusim v Launcher Icon Generator: ni uspeha
4.2) Poskusim v Generic Icon Generator: ni uspeha
5.) Na http://stackoverflow.com/questions/26287383/android-launcher-icon-too-small sem prebral, da je pomagalo, če niso uporabili generatorja in so sami izvozili primerne velikosti ikon za posamezne zaslone --> USPELOOOOOOOOO! :dancer: :dancers: 

P.S.: Ta issue puščam samo zato, da boš vidu kaj sm use že napisu, predn mi je v zadnjem poskusu, po tem k sm že vse prej napisu dejansk uspel :)

**Comment by NejcDraganjec** [comment]
Dobrodošel v svetu Jave, Googla in Androida :).

Najbolje povzamem s sledečim:
http://imgur.com/gallery/t0XHtgJ

in

http://www.globalnerdy.com/wordpress/wp-content/uploads/2014/07/android-programming.jpg

**Comment by ghost** [comment]
Haha me je pa nasmejalo :)
