### ISSUE TITLE
General slika

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#41]
Če v Adults/Urinary tract.../General kliknem sliko tabele se mi zaslon avtomatsko zarotira na landscape, potem lahko še enkrat kliknem sliko in mi jo odpre npr.kot v Google Slike (samo slika brez ostalega besedila). Potem kliknem na veliki X v zgornjem desnem robu v landscape načinu (ta je na voljo kot v Google Slike) in potem skoči nazaj na portrait mode.

Pogledal sem tudi povsod drugod v General kjer je slika in naredi isto. Čudno je to, da imam obračanje zaslona izključeno.

**Comment by NejcDraganjec** [comment]
Ja to je sprogramirano vedenje. Tako je prav in sicer program pogleda dimenzije slike in orientira zaslon tako, da jo lahko prikaže veliko kot se da. Je pa smotano ker se ob tej rotaciji proces ustavi in moraš potem na fotko še enkrat klikniti. To moram še preštudirat kaj je za narediti. To delovanje sem opisal tudi že v komentarju ene izmed starejših kartic.
