### ISSUE TITLE
Search napaka

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#42]
Konkretni primer: glej video
https://drive.google.com/file/d/0B0c8XrM0mazqV2x5LUFGTktpVXM/view?usp=sharing

**Comment by NejcDraganjec** [comment]
Popravljeno. Napaka je bila tudi na ostalih nivojih in ne le pri iskalnem zadetku na TItles2xx, kadar je najdena kategorija vodila direktno na therapy screen. Zapiram kartico.
