### ISSUE TITLE
'General' bug

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#43]
V linkanem videu poglej kaj dela s scroll barom na desni. To dela v obeh mojih napravah (Samsung Ace 2 in Note 4). Tudi če se skoncentriraš na vsebino 'General', se zadeve večkrat ponovijo.

Link: https://drive.google.com/file/d/0B0c8XrM0mazqR0VEQkFxQmk2N0k/view?usp=sharing

**Comment by NejcDraganjec** [comment]
Paše v kategorijo androidovih problemov s content providerjem (kar smo se mi pogovarjali o querijih). Še iščem rešitev...

**Comment by NejcDraganjec** [comment]
Aja, linka nisem pogledal, si pa mislim da krči in razteguje scroll bar. To je normalno vedenje. Da se vsebina ponavlja, kadar prideš do konca in se potem vračaš nazaj pa ni normalno.

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico...

**Comment by ghost** [comment]
Ok ne ponavlja veš, scroller baru pa še vedno dogaja :) to nisi potem našel rešitve, je android tak kot je?
