### ISSUE TITLE
Pathogen/S.pneumoniae bug

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#44]
V Excel datoteki, in se mi zdi da tudi v DB ima omenjen patogen 3 nivoje. Sprogramirano imamo, da imajo patogeni max 2 nivoja (glavni in možne podkategorije). Samo pri tem se pojavita 2 podkategoriji (meningitis,other infections) samo ene podkategorije (penicillin resistant (MIC  ≥ 2 ug/mL)). Se lahko doda še en nivo?

Problem je na obeh mojih napravah različno izražen. V Note4 se relativno lepo izrazi bug: pojavi se na videu slabo vidna črta (jo pokažem s prstom - @00:05), ki razmejuje doze podpodkategorij (meningitis,other infections) tako v Therapy of choice kot v Alternative therapy. Nikjer ne piše imen podpodkategorij (meningitis,other infections), kar bi popravili z zgoraj predlaganim.

V Samsung Ace2 pa aplikacija enostavno crash-a, ne glede na to katero podkategorijo klikem (penicillin susceptible(MIC < 0.1 ug/mL), penicillin intermediate (MIC 0.1 ug/mL), penicillin resistant (MIC  ≥ 2 ug/mL)).

Link: https://drive.google.com/file/d/0B0c8XrM0mazqblI0S0hsSzh1dGM/view?usp=sharing

**Comment by NejcDraganjec** [comment]
Ne, imamo sprogramirano na 3 nivoje. Nekje se mu nekaj zatkne. Bom preveril.

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico...
