### ISSUE TITLE
Adults/Neutropenic patient/General bug

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#45]
V Note4 mi izrisuje vsebino brez težav. V Samsung Ace2 pa svašta (v videu). Poleg tega, da ne vem kaj dogaja scroller bar-u, se zadnji odstavek pojavi z naslovom NEUTROPENIC PATIENT WITH FEVER (se ne bi smel in se v Note4 ne prikaže). Potem pa ko greš nazaj scrollat navzgor se pa magično pojavi ponovljen zadnji odstavek kot sedaj prvi odstavek :)

Link: https://drive.google.com/file/d/0B0c8XrM0mazqUi02MVVYTWpUSTg/view?usp=sharing

**Comment by NejcDraganjec** [comment]
Podvojena kartica. KOt odgovorjeno v par kartic spodaj, je vse to posledica androidovega content providerja. POdvajanje vsebine, pojavljanje anotacij na therapy screen... Še raziskujem kje je sploh problem, ker kar se kode tiče je vse prav in je izziv nekje globje v samem android sistemu.

Spreminjanje scroll bara je pa normalno.
