### ISSUE TITLE
Kratice v settings

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#46]
Kratice v settings, zdej so kar direkt pod settings. Bi se dal to fliknt pod settings/abreviations, tko da bi dejansko kliknu še en gumb ko imaš settings odprt, ne da je direktno pod 'Contact us' že celoten seznam kratic.

**Comment by NejcDraganjec** [comment]
Cel "settings", ki to v resnici sploh ni več, je bil predelan. Sedaj je čisto drugačni koncept z gumbki in Alert Dialogi. Zapiram kartico.
