### ISSUE TITLE
Slika v General

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#47]
V Adults/Upper respiratory tract/General je slika, k nad njo in pod njo avtomatično naredi par vrstic presledka.  Samo sem pogruntu, da naredi to kot nekakšn prostor za zoomiranje slike... je to tko mišlen al kaj je hec s tem?

**Comment by ghost** [comment]
https://drive.google.com/file/d/0B0c8XrM0mazqdlU1bVlGNzNEdHM/view?usp=sharing
Razmak v vseh General s slikami (konkretno je slikan Adults/Upper respiratory)

**Comment by NejcDraganjec** [comment]
Tako je mišljeno. Pros and cons, vedno :). Se pa da zdej lepo zoomirat.
