### ISSUE TITLE
Posodobitev teksta v Licence agreement ipd.

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#48]
Moraš mi pokazati, kje se to popravi v Android Studiu (če slučajno odideš v Njemačko, preden dobim Licence agreement).

**Comment by NejcDraganjec** [comment]
Sej ne grem na Mars, ampak sam dobre 4 ure vožnje stran. Na internetu pa itak vsak dan na razpolago :). Boš že poslal k boste imeli pa bom posodobil. Zaenkrat zapiram.

**Comment by ghost** [comment]
Deal :)
