### ISSUE TITLE
Razmak med ikono in tekstom v Main Screen/ Notes + Bookmarks (SAMSUNG ACE 2!!! Note 4 dela OK)

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#49]
Link: https://drive.google.com/open?id=0B0c8XrM0mazqbHJKeTUxVnZmMXFPUngtZzVtNEJ0NmxGempn&authuser=0

https://drive.google.com/open?id=0B0c8XrM0mazqMVlxblcxZldkR21VREpzLUstNkZnR19xcTFv&authuser=0

**Comment by NejcDraganjec** [comment]
Problemi s podporo RTL. In problem je specifičen za ta model, očitno. Pri ostalih mi podporne knjižnice omogočijo paddingStart in paddingEnd...

Dodal sem še paddingLeft in paddingRight. Zapiram kartico.
