### ISSUE TITLE
Pathogen / S.pneumoniae

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#51]
Ob kliku na zadnjo deep kategorijo (Meningitis / Other infection) se aplikacija sesuje. To konstantno dela na Samsung Ace 2, medtem ko je na Samsung Note 4 sesulo samo prvič ko sem poskusil. Ko se je ponovno zagnalo, je delalo naslednje 5krat kar sem poizkusil na tej napravi.

Potem se pa dogaja svašta na Ace 2 (ne morem reči, ali bi se dogajalo isto na Note4, ker se mi je sesulo samo enkrat, bi se pa verjetno kaj od sledečega pokazalo takoj, ko se je aplikacija restartala. Tako da sklepam, da Note 4 nima teh napak). Ko se ponovno zažene na Ace 2, te vrne avtomatsko na tisti nivo kjer se je aplikacija sesula (to je OK). Potem se lahko še malo igraš v Pathogens z drugimi patogeni in je vse OK. Potem pa prvič ko prideš nazaj na Main Screen te ponovno vpraša če sprejmeš Licence agreement (tisto z ovariji :) )

**Comment by NejcDraganjec** [comment]
WTF se je zgodilo... Ko sem to naredil in testiral je delalo... Bom preveril!

**Comment by NejcDraganjec** [comment]
Z aplikacijo je vse ok. Problem je v koruptirani bazi. Ko sta urejala sta mogla neki pobrkljat. Error, če vama bo pri debugingu kaj v pomoč, ki ga dobim je:

03-15 20:49:04.589: E/DefaultDatabaseErrorHandler(29423): Corruption reported by sqlite on database: /data/data/eu.anteros.quibasimpleguidetoantimicrobials/databases/quiba.sqlite
03-15 20:49:05.314: E/SQLiteDatabase(29423): PRAGMA integrity_check on /data/data/eu.anteros.quibasimpleguidetoantimicrobials/databases/quiba.sqlite returned: rowid 136 missing from index tbl_sys_pathogens_to_pharmaceuticgroups_to_therapytypes_5
03-15 20:49:05.444: E/AndroidRuntime(29423):    at eu.anteros.quibasimpleguidetoantimicrobials.finalScreens.pathogen_screen_fragment.onCreateView(pathogen_screen_fragment.java:178)

**Comment by ghost** [comment]
Ne vrže več ven, tako da je dokončano
