### ISSUE TITLE
Pathogen / S.pneumoniae / General in Refenreces

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#53]
Ne najdem že odprte kartice tukaj na Githubu, vem pa da smo o tem govorili, če ne drugje prek FB/skajpa/v živo. Zdaj smo pri parih patogenih (S.pneumoniae,...) dodali še eno podkategorijo. In sedaj imamo tam General in References, ker imamo pač tako sprogramiran ta drugi nivo še iz Adults in Children. 
Tukaj sta General in Reference odveč in bi layout uporabili od tistih podnivojev iz Adults/Children, ki nimajo več General + References.

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico.
