### ISSUE TITLE
Query napaka, ki je še ostala neodpravljena s prejšnjo rešitvijo ostalih query napak

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#54]
Children/Heart/Edocarditis/Targeted therapy --> sta 2 različni Targeted therapy (Targeted therapy-artificial valve in Targeted therapy - native valve) in obe imata med svojimi drugimi podkategorijami tudi Staphylococcal endocarditis. 

Problem je v zaslonu ki se odpre, ko kliknemo na Staphylococcal endocarditis (ne glede na Targeted therapy-artificial valve ali Targeted therapy - native valve). Odpre se 5 deep kategorij. Moralo bi biti tako, da sta 2.in 3.samo pri 'artificial valve', 1,4..in 5. pa pri 'native'

**Comment by NejcDraganjec** [comment]
Done and done... Zapiram kartico.
