### ISSUE TITLE
Spremeni 'Settings' ikono

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#56]
Glede na to, da res ni nobenih settingsov za urejat, bi bilo bolj smiselno spremeniti v info ikono.

**Comment by ghost** [comment]
Nejc naj popravi samo ime v orodni vrstici iz Settings v Information

**Comment by NejcDraganjec** [comment]
Sem tudi ikono zamenjal. Pro bono oz za blagovno menjavo "pivce za živce" ;). Zapiram kartico.
