### ISSUE TITLE
Renewal tekst grammar check

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#57]
sam par slovničnih: 
Quiba Licence...---> Quiba License..
...is never ending story...---> is a never...
...renew your licence...-->... license...
Just press 'RENEVE' buton ---> Just press 'RENEW' button
...Google Play store where...-->...Google Play store, where...
...where you click on button...--->...where you click on the button...
...takes is couple... --> takes is a couple...

**Comment by NejcDraganjec** [comment]
Done. Zapiram kartico.
