### ISSUE TITLE
Main menu / Prevention / vsi General teksti

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#58]
copy/paste FB:
neki sva opazla. Main screen/Prevention povsod kjer je General je napacna vsebina. In poj sva hotla popravt v databazi pa sploh ne znava pridt do tja. To je tisto k smo mel na zacetku Medical prophilaxis in je v tbl_list_categories_primary. To je kul. Sam poj smo pa spremenil to v gumb Prevention v Main screenu. In v tej tabeli sploh ni Prevention napisanga. V glavnem zajema ta del aplikacije General dele iz Adults dela (od sepse, Cžs pa od Eyes, en General je celo prazen). Sklepava da je to podobna query napaka kot smo imeli s kategorijami.

**Comment by NejcDraganjec** [comment]
Done and done. Zapiram kartico.
