### ISSUE TITLE
Abbreviations and acronyms - slovnične napake 

### ISSUE THREAD

**Issue by Valentina91** [NejcDraganjec/Qiuba_BugTrack#59]
ELISA, enzyme immunoassay [AU: ELISA is the standard abbreviation for this] --> ELISA, enzyme immunoassay 
ETEC, enterotoxigenic E. col --> ETEC, enterotoxigenic E. coli
VISA, vancomycin intermediate Staphylococcus aureus --> VISA, vancomycin-intermediate Staphylococcus aureus
VRE, vancomycin resistant enterococcus --> VRE, vancomycin-resistant enterococcus
VRSA, vancomycin resistant Staphylococcus aureus --> VRSA, vancomycin-resistant Staphylococcus aureus

EHEC in EIEC naj bosta vsak v svojem okencu (sedaj sta v istem).

**Comment by NejcDraganjec** [comment]
Done.
