### ISSUE TITLE
Ime aplikacije - samo 'Quiba'

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#7]
Ime aplikacije naj bo pred zagonom aplikacije na namizju  samo 'Quiba', v orodni vrstici v aplikaciji pa 'Quiba - Simple Guide to Antimicrobials'

**Comment by ghost** [comment]
P.S.: Ime aplikacije naj bo pred zagonom aplikacije na namizju samo 'Quiba', v orodni vrstici v aplikaciji pa enako 'Quiba'.
Puščam odprto do naslednjega zbildanega APK-ja

**Comment by NejcDraganjec** [comment]
Rešeno v zadnjem bildu, ki sem ti ga poslal včerej. Ponovno zapiram kartico :).
