### ISSUE TITLE
Database Issue - ponovljeni vnosi terapij

### ISSUE THREAD

**Issue by ghost** [NejcDraganjec/Qiuba_BugTrack#8]
tbl_therapy_dosages: vnosi 13, 15, 17 so vsebinsko enaki, a jih zaradi slovničnih napak dovoli več kot enkrat napisat

Vsebinska napaka: rifampicin mora biti preveden v rifampin

**Comment by NejcDraganjec** [comment]
Domnevam da je to zdej že porihtano, ali pa da vsaj aktivno na tem delata in bo danes/jutri. Tako da pipsam hrošča.

**Comment by ghost** [comment]
Tako je, to je zdaj urejeno, zaenkrat pa pustiva to še kot issue, da bom še preveril v databazi, da bo za ziher.

**Comment by NejcDraganjec** [comment]
OK. Potem pa zapri ko potrdiš da zadeve štimajo.
